version: '3.5'

services:
  etl:
    image: harbor.honeur.org/etl-sourasky/etl:current
    volumes:
      - "./log:/log"
      - "/Users/silviajimeneznavarro/Dev/data/Sourasky_ETL/v18:/data"
    networks:
      - honeur-net
    environment:
      DB_DBMS: "postgresql"
      DB_SERVER : "postgres"
      DB_PORT: "5432"
      DB_DBNAME: "OHDSI"
      DB_SCHEMA: omopcdm
      DB_USER: feder8_admin
      DB_PASSWORD: feder8_admin
      LAST_DATA_EXPORT: "2024-01-01"
      VERBOSITY_LEVEL: INFO
      DELIMITER: ;
      ETL_DATE_FORMAT: etl_date_format
      ETL_FILENAME_DEMOGRAPHICS: "demographics.csv"
      ETL_FILENAME_DISEASE_ADMISSION: "disease_admission.csv"
      ETL_FILENAME_DISEASE_AMBULATORY: "disease_ambulatory.csv"
      ETL_FILENAME_DISEASE_CHARACTERISTICS_MYELOMA: "disease_characteristics_myeloma.csv"
      ETL_FILENAME_DISEASE_CHRONICDIAGNOSIS: "disease_chronicdiagnosis.csv"
      ETL_FILENAME_DISEASE_HEMATODIAGNOSIS: "disease_hematodiagnosis.csv"
      ETL_FILENAME_LAB_DATA_CYTOGENETICS: "lab_data_cytogenetics.csv"
      ETL_FILENAME_LAB_DATA_FISH: "lab_data_fish.csv"
      ETL_FILENAME_LAB_DATA_TEST: "lab_data_test.csv"
      ETL_FILENAME_TREATMENT_CATO: "treatment_cato.csv"
      ETL_FILENAME_TREATMENT_MAP: "treatment_map.csv"
      ETL_FILENAME_TREATMENT_MEDICATION: "treatment_medication.csv"
      ETL_FILENAME_BODY_MEAS: "body_measurements.csv"
      ETL_FILENAME_IMMUNOFIXATION: "immunofixation.csv"
      ETL_ENCODING_DEMOGRAPHICS: "utf-8"
      ETL_ENCODING_DISEASE_ADMISSION: "utf-8"
      ETL_ENCODING_DISEASE_AMBULATORY: "utf-8"
      ETL_ENCODING_DISEASE_CHARACTERISTICS_MYELOMA: "utf-8"
      ETL_ENCODING_DISEASE_CHRONICDIAGNOSIS: "utf-8"
      ETL_ENCODING_DISEASE_HEMATODIAGNOSIS: "utf-8"
      ETL_ENCODING_LAB_DATA_FISH: "utf-8"
      ETL_ENCODING_LAB_DATA_CYTOGENETICS: "utf-8"
      ETL_ENCODING_LAB_DATA_TEST: "utf-8"
      ETL_ENCODING_TREATMENT_CATO: "utf-8"
      ETL_ENCODING_TREATMENT_MAP: "utf-8"
      ETL_ENCODING_TREATMENT_MEDICATION: "utf-8"
      ETL_ENCODING_BODY_MEAS: "utf-8"
      ETL_ENCODING_IMMUNOFIXATION: "utf-8"
networks:
  honeur-net:
    external:
      name: feder8-net
